### ISSUE TITLE
Doesn't build with ghc 8.0.1

### ISSUE THREAD

**Issue by DevraRabbit** [chetant/LibClang#64]
Heyo

I installed ghc 8.0.1 and cabal 1.25 and no matter how I try to build it it doesn't compile. When trying to compile the Setup.hs from the master branch is says:

Setup.hs:272:84: error:
    Not in scope: type constructor or class ‘LibraryName’

When I try installing it with cabal the error message is:

src/ErrMonad.lhs:42:10: error:
    • No instance for (Applicative (ErrM a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monad (ErrM a)’
cabal: Leaving directory '/tmp/cabal-tmp-4902/greencard-3.0.4.2'
cabal: Error: some packages failed to install:
LibClang-0.1.0-JWbxC2bC4YSHhNKAX6WBhy depends on LibClang-0.1.0 which failed
to install.
greencard-3.0.4.2-CIO3I1N7VPbLpRLRYOkKRW failed during the building phase. The
exception was:
ExitFailure 1

Thanks for the Help

**Comment by chetant** [comment]
@DevraRabbit Could you try with the latest release?

**Comment by chetant** [comment]
no update here, please reopen if its still failing with the latest release
